name: internal_publishing
on:
  push:
    branches: "VCUE-1173"
  workflow_dispatch:
#on:
#  workflow_dispatch:
#  workflow_run:
#    workflows: ["release"]
#    types:
#      - completed

#     ${{ github.event.workflow_run.conclusion == 'success' }} &&
jobs:
  publish:
    name: "internal publishing"
    if: |
      ( github.actor == 'matteo-chesi' )
    runs-on: chesim-zinal-login
    steps:
      - uses: actions/checkout@v4

      - name: publish
        env:
          TAG: ${{ github.ref_name }}
        run: |
          .github/release/publish.sh ${TAG}
