name: internal_publishing
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

jobs:
  publish:
    name: internal publishing
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: github.actor == 'matteo-chesi'
    runs-on: chesim-zinal-login
    steps:
      - uses: actions/checkout@v4

      - name: publish
        env:
          TAG: ${{ github.ref_name }}
        run: |
          .github/release/publish.sh
